export const CourseList = [
  { course: "B.E(Automobile Engineering)" },
  { course: "B.E(Biomedical Engineering)" },
  { course: "B.E(Civil Engineering)" },
  { course: "B.E(Computer Science and Engineering(AI and ML))" },
  { course: "B.E(Computer Science and Engineering)" },
  { course: "B.E(Electrical and Electronics Engineering)" },
  { course: "B.E(Electronics and Communication Engineering)" },
  { course: "B.E(Instrumentation and Control Engineering)" },
  { course: "B.E(Mechanical Engineering)" },
  { course: "B.E(Metallurgical Engineering)" },
  { course: "B.E(Production Engineering)" },
  { course: "B.E(Robotics and Automation)" },
  { course: "B.Tech(Bio Technology)" },
  { course: "B.Tech(Fashion Technology)" },
  { course: "B.Tech(Information Technology" },
  { course: "B.Tech(Textile Technology" },
  { course: "B.E(Electrical and Electronics Engineering)(Sandwich)" },
  { course: "B.E(Mechanical Engineering)(Sandwich)" },
  { course: "B.E(Production Engieering)(Sandwich)" },
  { course: "B.E(Robotics and Automation)" },
  { course: "M.E(Applied Electronics)" },
  { course: "M.E(Automative Engineering)" },
  { course: "M.E(Biometrics and Cybersecurity)" },
  { course: "M.E(Communication Systems)" },
  { course: "M.E(Computer Integrated Manufacturing)" },
  { course: "M.E(Computer Science and Engineering)" },
  { Course: "M.E(Control Systems)" },
  { Course: "M.E(Embedded & Real-Time-Systems)" },
];
