export const courseList = [
  { course: "B.E (Automobile Engineering)" },
  { course: "B.E (Biomedical Engineering)" },
  { course: "B.E (Civil Engineering)" },
  { course: "B.E (Computer Science and Engineering (AI and ML))" },
  { course: "B.E (Computer Science and Engineering)" },
  { course: "B.E (Electrical and Electronics Engineering)" },
  { course: "B.E (Electronics and Communication Engineering)" },
  { course: "B.E (Instrumentation and Control Engineering)" },
  { course: "B.E (Mechanical Engineering)" },
  { course: "B.E (Metallurgical Engineering)" },
  { course: "B.E (Production Engineering)" },
  { course: "B.E (Robotics and Automation)" },
  { course: "B.Tech (Bio Technology)" },
  { course: "B.Tech (Fashion Technology)" },
  { course: "B.Tech (Information Technology)" },
  { course: "B.Tech (Textile Technology)" },
  { course: "B.E (Electrical and Electronics Engineering) (Sandwich)" },
  { course: "B.E (Mechanical Engineering) (Sandwich)" },
  { course: "B.E (Production Engieering) (Sandwich)" },
  { course: "B.E (Robotics and Automation)" },
  { course: "M.E (Applied Electronics)" },
  { course: "M.E (Automative Engineering)" },
  { course: "M.E (Biometrics and Cybersecurity)" },
  { course: "M.E (Communication Systems)" },
  { course: "M.E (Computer Integrated Manufacturing)" },
  { course: "M.E (Computer Science and Engineering)" },
  { course: "M.E (Control Systems)" },
  { course: "M.E (Embedded & Real-Time-Systems)" },
  { course: "M.E (Energy Engineering)" },
  { course: "M.E (Engineering Design)" },
  { course: "M.E (Industrial Engineering)" },
  { course: "M.E (Industrial Metallurgy)" },
  { course: "M.E (Infrastructure Engineering)" },
  { course: "M.E (Manufacturing Engineering)" },
  { course: "M.E (Power Electronics and Drives)" },
  { course: "M.E (Structural Engineering)" },
  { course: "M.E (VLSI Design)" },
  { course: "M.Tech (Bio Technology)" },
  { course: "M.Tech (Information Technology)" },
  { course: "M.Tech (Nano Science and Technology)" },
  { course: "M.Tech (Textile Technology)" },
  { course: "Master of Computer Applications" },
  { course: "M.Sc (Fashion Design & Merchandising - 5 Years Integrated)" },
  { course: "M.Sc (Applied Mathematics)" },
  { course: "M.Sc (Software Systems - 5 Years Integrated)" },
  { course: "M.Sc (Theoretical Computer Scient - 5 Years Integrated)" },
  { course: "M.Sc (Data Science - 5 Years Integrated)" },
  { course: "M.Sc (Cyber Security - Integrated - 5 Years Integrated)" },
  { course: "BSc (Applied Science)" },
  { course: "BSc (Computer Systems and Design)" },
  { course: "MBA" },
  { course: "MBA (Waste Management & Social Entrepreneurship)" },
];
