export const data = [
  {
    id: 1,
    name: "Person 1",
    dept: "I - Web development",
    role: "Team Leader",
    industry: "Software",
    companyName: "ABC Company",
    city: "Chennai",
    region: "Tamilnadu",
    years: "2 years",
    servicesOffered: "Webhosting, Webdevelopment",
    image:
      "https://img.freepik.com/free-photo/portrait-white-man-isolated_53876-40306.jpg?size=626&ext=jpg&ga=GA1.2.546867582.1692711868&semt=ais",

    dob: "03-03-1986",
    interest: "Reading Books, Watching movies",
    phone: "+91-8778833937",
  },
  {
    id: 2,
    name: "Person 2",
    dept: "Marketing",
    role: "Marketing Manager",
    industry: "Advertising",
    companyName: "XYZ Agency",
    city: "New York",
    region: "New York",
    years: "5 years",
    servicesOffered: "Digital Marketing, Campaigns",
    image:
      "https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg?size=626&ext=jpg&ga=GA1.2.546867582.1692711868&semt=ais",

    dob: "10-12-1982",
    interest: "Traveling, Photography",
    phone: "+91-9988776655",
  },
  {
    id: 3,
    name: "Person 3",
    dept: "Sales",
    role: "Sales Executive",
    industry: "Retail",
    companyName: "123 Mart",
    city: "Los Angeles",
    region: "California",
    years: "1 year",
    servicesOffered: "Customer Relationship, Sales",
    image:
      "https://img.freepik.com/free-photo/portrait-young-confident-businessman-wearing-glasses_158595-5360.jpg?size=626&ext=jpg&ga=GA1.2.546867582.1692711868&semt=ais",

    dob: "05-08-1990",
    interest: "Hiking, Cooking",
    phone: "+91-9988776655",
  },
  {
    id: 4,
    name: "Person 4",
    dept: "Finance",
    role: "Financial Analyst",
    industry: "Finance",
    companyName: "Global Finance Corp",
    city: "London",
    region: "England",
    years: "3 years",
    servicesOffered: "Financial Planning, Investment Analysis",
    image:
      "https://img.freepik.com/free-photo/smiling-caucasian-guy-with-beard-looking-happy_176420-18707.jpg?size=626&ext=jpg&ga=GA1.2.546867582.1692711868&semt=ais",

    dob: "11-09-1988",
    interest: "Playing Guitar, Yoga",
    phone: "+91-9988776655",
  },
  {
    id: 5,
    name: "Person 5",
    dept: "Engineering",
    role: "Software Engineer",
    industry: "Technology",
    companyName: "Tech Innovators",
    city: "San Francisco",
    region: "California",
    years: "4 years",
    servicesOffered: "Software Development, Code Review",
    image:
      "https://img.freepik.com/free-photo/young-woman-with-round-glasses-yellow-sweater_273609-7091.jpg?size=626&ext=jpg&ga=GA1.2.546867582.1692711868&semt=ais",

    dob: "07-06-1992",
    interest: "Gaming, Programming",
    phone: "+91-9988776655",
  },
  {
    id: 6,
    name: "Person 6",
    dept: "Human Resources",
    role: "HR Manager",
    industry: "HR Consulting",
    companyName: "PeopleFirst",
    city: "Sydney",
    region: "New South Wales",
    years: "6 years",
    servicesOffered: "Talent Acquisition, Employee Relations",
    image:
      "https://img.freepik.com/free-photo/cheerful-curly-business-girl-wearing-glasses_176420-206.jpg?size=626&ext=jpg&ga=GA1.2.546867582.1692711868&semt=ais",

    dob: "09-18-1985",
    interest: "Painting, Traveling",
    phone: "+91-9988776655",
  },
  {
    id: 7,
    name: "Person 7",
    dept: "Operations",
    role: "Operations Manager",
    industry: "Logistics",
    companyName: "Swift Logistics",
    city: "Tokyo",
    region: "Kanto",
    years: "7 years",
    servicesOffered: "Supply Chain Management, Process Optimization",
    image:
      "https://img.freepik.com/free-photo/beautiful-male-half-length-portrait-isolated-white-studio-background-young-emotional-hindu-man-blue-shirt-facial-expression-human-emotions-advertising-concept-standing-smiling_155003-25250.jpg?size=626&ext=jpg&ga=GA1.2.546867582.1692711868&semt=ais",

    dob: "12-25-1979",
    interest: "Gardening, Meditation",
    phone: "+91-9988776655",
  },
  {
    id: 8,
    name: "Person 8",
    dept: "Design",
    role: "Graphic Designer",
    industry: "Design",
    companyName: "Creative Designs Inc",
    city: "Paris",
    region: "Ile-de-France",
    years: "2 years",
    servicesOffered: "Logo Design, Illustration",
    image:
      "https://img.freepik.com/free-photo/close-up-shot-friendly-looking-elegant-young-african-american-female-with-straight-dark-straight-hair-having-happy-joyful-look-posing_344912-1016.jpg?size=626&ext=jpg&ga=GA1.2.546867582.1692711868&semt=ais",

    dob: "04-30-1994",
    interest: "Sketching, Music",
    phone: "+91-9988776655",
  },
  {
    id: 9,
    name: "Person 9",
    dept: "Research",
    role: "Research Scientist",
    industry: "Science",
    companyName: "Innovate Labs",
    city: "Berlin",
    region: "Berlin",
    years: "8 years",
    servicesOffered: "Scientific Research, Data Analysis",
    image:
      "https://img.freepik.com/free-photo/bohemian-man-with-his-arms-crossed_1368-3542.jpg?size=626&ext=jpg&ga=GA1.2.546867582.1692711868&semt=ais",

    dob: "02-15-1980",
    interest: "Reading Journals, Hiking",
    phone: "+91-9988776655",
  },
  {
    id: 10,
    name: "Person 10",
    dept: "Management",
    role: "General Manager",
    industry: "Business",
    companyName: "Global Enterprises",
    city: "Beijing",
    region: "Beijing",
    years: "9 years",
    servicesOffered: "Strategic Planning, Team Leadership",
    image:
      "https://img.freepik.com/free-photo/pretty-smiling-joyfully-female-with-fair-hair-dressed-casually-looking-with-satisfaction_176420-15187.jpg?size=626&ext=jpg&ga=GA1.2.546867582.1692711868&semt=ais",

    dob: "06-20-1976",
    interest: "Playing Chess, Cooking",
    phone: "+91-9988776655",
  },
];

export default data;
