export const data = [
  {
    _id: "650eb685aba7394f1e16ac47",
    profileId: "d04fc2a6-e383-4bcb-85b3-4588b350de84",
    name: "Sadhanandh Mariadoss",
    image: "",
    course: "Civil",
    year: 1987,
    location: "Coimbatore, Tamilnadu, India",
    phone: 8765432109,
    company: "Maxcon Town Planning & Development Private Limited",
    designation: "Managing Director / Principal Consultant",
    industry: "Manufacturing",
    offers: "Automotive Parts, Machinery, Textiles",
    linkedin: "https://www.linkedin.com/in/example2",
    website: "https://www.example2.com",
    __v: 0,
  },
  {
    _id: "650eb7a8aba7394f1e16ac49",
    profileId: "3adb69f2-2f5e-4e59-b0d1-1f1c02a68374",
    name: "Jeganathan Annamalai",
    image: "",
    course: "Civil",
    year: 1979,
    location: "Coimbatore, Tamilnadu, India",
    phone: 8765432109,
    company: "Maxcon Town Planning & Development Private Limited",
    designation: "Managing Director / Principal Consultant",
    industry: "Manufacturing",
    offers: "Automotive Parts, Machinery, Textiles",
    linkedin: "https://www.linkedin.com/in/example2",
    website: "https://www.example2.com",
    __v: 0,
  },
  {
    _id: "650ebb81aba7394f1e16ac4c",
    profileId: "8cb53671-0363-4ac1-a4c6-38b6048a5e88",
    name: "Ganesh Gopalakrishnan",
    image: "",
    course: "ME(sandwich)",
    year: 1994,
    location: "Trichy, Tamilnadu, India",
    phone: 6543210987,
    company: "GeakMinds,Inc",
    designation: "CEO",
    industry: "Healthcare",
    offers: "Medical Equipment, Pharmaceuticals, Telemedicine",
    linkedin: "https://www.linkedin.com/in/example4",
    website: "https://www.example4.com",
    __v: 0,
  },
  {
    _id: "650ebc6caba7394f1e16ac4e",
    profileId: "180e6b4e-665c-44a5-a001-5456e2dfda2d",
    name: "Yuvanesan Muthukumaresan",
    image: "",
    course: "ME(sandwich)",
    year: 2011,
    location: "Madurai, Tamilnadu, India",
    phone: 7654321098,
    company: "Sivanesan Company",
    designation: "Operations Executive ",
    industry: "Defence",
    offers: "Aerospace Systems, Armored Vehicles, Cybersecurity",
    linkedin: "https://www.linkedin.com/in/example3",
    website: "https://www.example3.com",
    __v: 0,
  },
  {
    _id: "650ebd96aba7394f1e16ac50",
    profileId: "69d44a06-22a4-428a-8e23-b9f6a04f3584",
    name: "Udayakumar Murugan",
    image: "",
    course: "EEE",
    year: 2002,
    location: "Salem, Tamilnadu, India",
    phone: 5432109876,
    company: "CannyMinds Technology Solutions",
    designation: "Founder and CEO",
    industry: "Finance",
    offers: "Banking, Investment Management, Insurance Services",
    linkedin: "https://www.linkedin.com/in/example5",
    website: "https://www.example5.com",
    __v: 0,
  },
  {
    _id: "650ebf84aba7394f1e16ac5a",
    profileId: "caeb9128-5b3e-4c0f-b2e6-6cec68bdc2e9",
    name: "Sadhanandh Mariadoss",
    image: "",
    course: "Civil",
    year: 1987,
    location: "Erode, Tamilnadu, India",
    phone: 4321098765,
    company: "Maxcon Town Planning & Development Private Limited",
    designation: "Managing Director / Principal Consultant",
    industry: "Education",
    offers: "K-12 Education, Higher Education, Online Learning",
    linkedin: "https://www.linkedin.com/in/example6",
    website: "https://www.example6.com",
    __v: 0,
  },
  {
    _id: "650ec43faba7394f1e16ac5c",
    profileId: "2cc1978a-748e-4b9f-ab2f-beffd30927ec",
    name: "Pandiarajan S",
    image: "",
    course: "CSE",
    year: 2004,
    location: "Vellore, Tamilnadu, India",
    phone: 3210987654,
    company: "CredWealth Technologies Private Limited",
    designation: "CEO",
    industry: "Retail",
    offers: "Fashion, Electronics, Groceries",
    linkedin: "https://www.linkedin.com/in/example7",
    website: "https://www.example7.com",
    __v: 0,
  },
  {
    _id: "650ec4c9aba7394f1e16ac5e",
    profileId: "728584fa-60a8-4ad3-961f-3b367139652c",
    name: "Manish Ramakrishnan",
    image: "",
    course: "ECE",
    year: 1987,
    location: "Tirunelveli, Tamilnadu, India",
    phone: 2109876543,
    company: "Plant Engineering at Ashok Leyland",
    designation: "AGM",
    industry: "Telecommunications",
    offers: "Mobile Services, Internet Providers, Telecom Infrastructure",
    linkedin: "https://www.linkedin.com/in/example8",
    website: "https://www.example8.com",
    __v: 0,
  },
  {
    _id: "650ec7bcaba7394f1e16ac60",
    profileId: "10a9c73d-2e30-46b7-a00b-b9c42bbe4843",
    name: "Meyyappan Veerappan",
    image: "",
    course: "ME(Sandwich)",
    year: 2008,
    location: "Kanchipuram, Tamilnadu, India",
    phone: 1098765432,
    company: "Ferrament Global Technological Solutions",
    designation: "Business Partner",
    industry: "Hospitality",
    offers: "Hotels, Restaurants, Travel Services",
    linkedin: "https://www.linkedin.com/in/example9",
    website: "https://www.example9.com",
    __v: 0,
  },
  {
    _id: "650ec8f5aba7394f1e16ac62",
    profileId: "1a5de22b-24c0-4004-b264-ef7d86d8cc15",
    name: "Thirunavukarasu Thirunavukarasu",
    image: "",
    course: "ME(Sandwich)",
    year: 2009,
    location: "Tiruchirapalli, Tamilnadu, India",
    phone: 1987654321,
    company: "AgamWorks Tech Solutions Private Limited",
    designation: "SS,Founder & CEO ",
    industry: "Automotive",
    offers: "Car Manufacturing, Auto Parts, Electric Vehicles",
    linkedin: "https://www.linkedin.com/in/example10",
    website: "https://www.example10.com",
    __v: 0,
  },
  {
    _id: "650ec93daba7394f1e16ac64",
    profileId: "b5005933-079f-40ae-b548-f8fe133fee7d",
    name: "Palimar Rao",
    image: "",
    course: "ME(Sandwich)",
    year: 1984,
    location: "Tiruchirapalli, Tamilnadu, India",
    phone: 1987654321,
    company: "AgamWorks Tech Solutions Private Limited",
    designation: "SS,Founder & CEO ",
    industry: "Automotive",
    offers: "Car Manufacturing, Auto Parts, Electric Vehicles",
    linkedin: "https://www.linkedin.com/in/example11",
    website: "https://www.example11.com",
    __v: 0,
  },
  {
    _id: "650ec98eaba7394f1e16ac66",
    profileId: "903003e7-dfd0-4fd2-8983-bf02dc0612f4",
    name: "Dr V Sriram",
    image: "",
    course: "Mech",
    year: 1974,
    location: "Tiruchirapalli, Tamilnadu, India",
    phone: 1987654321,
    company: "SriramSafty",
    designation: "SS,Founder & CEO ",
    industry: "Automotive",
    offers: "Car Manufacturing, Auto Parts, Electric Vehicles",
    linkedin: "https://www.linkedin.com/in/example12",
    website: "https://www.example12.com",
    __v: 0,
  },
  {
    _id: "650ecac4aba7394f1e16ac68",
    profileId: "80edae20-a470-409e-88d9-46b80feccd25",
    name: "Karunanithi Daivasigamani",
    image: "",
    course: "Mech",
    year: 1994,
    location: "Dindigul, Tamilnadu, India",
    phone: 9987658921,
    company: "HK POLYTECH SOLUTIONS",
    designation: "Metallurgical,Proprietor ",
    industry: "Energy",
    offers: "Renewable Energy, Oil & Gas, Power Generation",
    linkedin: "https://www.linkedin.com/in/example14",
    website: "https://www.example14.com",
    __v: 0,
  },
  {
    _id: "650ecb5aaba7394f1e16ac6a",
    profileId: "9753f74f-68c8-4938-ae67-7f4b950ea106",
    name: "Saravanakumar S",
    image: "",
    course: "Mech",
    year: 2001,
    location: "Dindigul, Tamilnadu, India",
    phone: 9987654321,
    company: "HK POLYTECH SOLUTIONS",
    designation: "Metallurgical,Proprietor ",
    industry: "Energy",
    offers: "Renewable Energy, Oil & Gas, Power Generation",
    linkedin: "https://www.linkedin.com/in/example15",
    website: "https://www.example15.com",
    __v: 0,
  },
  {
    _id: "650ecc0aaba7394f1e16ac6c",
    profileId: "fb770367-faf3-48f5-8785-5edb79022365",
    name: "Senthil Kumar",
    image: "",
    course: "ME (Sandwich)",
    year: 1998,
    location: "Nagarcoil, Tamilnadu, India",
    phone: 9783654321,
    company: "ADITHYA TEKHNOLOGIES",
    designation: "Metallurgical,Proprietor ",
    industry: "Transportation",
    offers: "Logistics, Public Transit, Shipping Services",
    linkedin: "https://www.linkedin.com/in/example16",
    website: "https://www.example16.com",
    __v: 0,
  },
  {
    _id: "650ecea9aba7394f1e16ac6e",
    profileId: "d3ae2673-95a9-44ba-b583-89b8df1e1db9",
    name: "Panneer Selvam Subbiah",
    image: "",
    course: "EEE",
    year: 1984,
    location: "Kumbakonam, Tamilnadu, India",
    phone: 9783654821,
    company: "JL SEAGULL POWER PRODUCTS",
    designation: "DIRECTOR ",
    industry: "Pharmaceuticals",
    offers:
      "Drug Manufacturing, Research & Development, Pharmaceutical Distribution",
    linkedin: "https://www.linkedin.com/in/example17",
    website: "https://www.example17.com",
    __v: 0,
  },
  {
    _id: "650ecf89aba7394f1e16ac70",
    profileId: "812f96e5-eda7-4351-8145-2e86449da266",
    name: "Siddharth Anbuselvan",
    image: "",
    course: "BE (Sandwich)",
    year: 2014,
    location: "Hosur, Tamilnadu, India",
    phone: 9783754821,
    company: "Indsat Corporation",
    designation: "Head of Strategy & Planning ",
    industry: "Biotechnology",
    offers: "Biotech Research, Medical Devices, Genetic Engineering",
    linkedin: "https://www.linkedin.com/in/example18",
    website: "https://www.example18.com",
    __v: 0,
  },
  {
    _id: "650ed069aba7394f1e16ac72",
    profileId: "82ad14ab-01e4-4ca2-a40e-230490f36561",
    name: "Pravin Rajan",
    image: "",
    course: "BE (Sandwich)",
    year: 2010,
    location: "Pollachi, Tamilnadu, India",
    phone: 1098765432,
    company: "Sharp Garuda Farm Equipments P Ltd",
    designation: "AU,Managing Director",
    industry: "Textiles",
    offers: "Fabric Manufacturing, Clothing Production, Textile Design",
    linkedin: "https://www.linkedin.com/in/example19",
    website: "https://www.example19.com",
    __v: 0,
  },
  {
    _id: "650ed41faba7394f1e16ac74",
    profileId: "43d185bb-b3b2-4888-b1c8-fe9985de33e2",
    name: "Saravana Perumal Ramaswamy",
    image: "",
    course: "BE (Sandwich)",
    year: 1974,
    location: "Ramanathapuram, Tamilnadu, India",
    phone: 7798765432,
    company: "PURE AND POSITIVE ENERGY BUSINESS SOLUTIONS",
    designation: "Textile,Co founder ",
    industry: "Textiles",
    offers: "Fabric Manufacturing, Clothing Production, Textile Design",
    linkedin: "https://www.linkedin.com/in/example20",
    website: "https://www.example20.com",
    __v: 0,
  },
  {
    _id: "650ed4eaaba7394f1e16ac76",
    profileId: "012d6f55-e095-4040-ac3c-92a7f36fcb6a",
    name: "Lakshmi Narasimha Moorthy",
    image: "",
    course: "Mech",
    year: 1996,
    location: "Karaikudi, Tamilnadu, India",
    phone: 9876543210,
    company: "nichebrains",
    designation: "Cofounder & CEO",
    industry: "Food & Beverage",
    offers: "Food Processing, Restaurants, Beverage Production",
    linkedin: "https://www.linkedin.com/in/example21",
    website: "https://www.example21.com",
    __v: 0,
  },
  {
    _id: "650ed5e2aba7394f1e16ac78",
    profileId: "2d86ce59-462d-4bdd-89b0-823f651a77d8",
    name: "Srinivasan Thiagarajan",
    image: "",
    course: "ECE",
    year: 1972,
    location: "Ooty, Tamilnadu, India",
    phone: 9876587210,
    company: "Mel Systems And Services Ltd",
    designation: "President",
    industry: "Tourism",
    offers: "Travel Agencies, Hospitality, Tour Packages",
    linkedin: "https://www.linkedin.com/in/example22",
    website: "https://www.example22.com",
    __v: 0,
  },
  {
    _id: "650ed67aaba7394f1e16ac7a",
    profileId: "821e96c0-5f93-4039-ac19-33fa5ae55a69",
    name: "Vignesh Swaminathan",
    image: "",
    course: "ECE",
    year: 1998,
    location: "Dharmapuri, Tamilnadu, India",
    phone: 7654321098,
    company: "Amaravel Group",
    designation: "Director",
    industry: "Chemicals",
    offers: "Chemical Manufacturing, Chemical Research, Specialty Chemicals",
    linkedin: "https://www.linkedin.com/in/example23",
    website: "https://www.example23.com",
    __v: 0,
  },
  {
    _id: "650edc79aba7394f1e16ac7c",
    profileId: "88c76f10-585c-4ffe-acb4-29f7032d7366",
    name: "Ashok Kumar",
    image: "",
    course: "BE / B.Tech ECE",
    year: 2007,
    location: "Villupuram, Tamilnadu, India",
    phone: 5432109876,
    company: "Wootz Metal Solutions India Private Limited",
    designation: "Metallurgical,Founder ",
    industry: "Real Estate",
    offers:
      "Property Development, Real Estate Consulting, Construction Services",
    linkedin: "https://www.linkedin.com/in/example25",
    website: "https://www.example25.com",
    __v: 0,
  },
  {
    _id: "650edd20aba7394f1e16ac7e",
    profileId: "b248f2f3-77ce-487d-8d5a-c03717ded1d1",
    name: "Vijayakumar Subbaiah",
    image: "",
    course: "BE / B.Tech ME (Sandwich)",
    year: 1994,
    location: "Neyveli, Tamilnadu, India",
    phone: 4321098765,
    company: "Vees Star Diamonds and Jewelry",
    designation: "Partner",
    industry: "Mining",
    offers: "Coal Mining, Mineral Extraction, Mining Services",
    linkedin: "https://www.linkedin.com/in/example26",
    website: "https://www.example26.com",
    __v: 0,
  },
  {
    _id: "650ede6daba7394f1e16ac80",
    profileId: "f0de3416-1501-4fa8-ab97-48b9af5f1338",
    name: "Radhakrishnan Nambiar",
    image: "",
    course: "BE / B.Tech EEE",
    year: 1984,
    location: "Arakkonam, Tamilnadu, India",
    phone: 3210987654,
    company: "Agnus Management Partners",
    designation: "CEO",
    industry: "Aviation",
    offers: "Aircraft Manufacturing, Aerospace Engineering, Airline Services",
    linkedin: "https://www.linkedin.com/in/example27",
    website: "https://www.example27.com",
    __v: 0,
  },
  {
    _id: "650edf07aba7394f1e16ac82",
    profileId: "ca386e19-b24a-4b4e-8e04-d00a952c82a6",
    name: "Ganeshan Suppiah",
    image: "",
    course: "BE / B.Tech ME (Sandwich)",
    year: 1994,
    location: "Tambaram, Tamilnadu, India",
    phone: 3218987654,
    company: "MSD (Meenu Subbiah Diamonds)",
    designation: "Partner",
    industry: "Legal Services",
    offers: "Legal Consultation, Litigation Support, Corporate Law",
    linkedin: "https://www.linkedin.com/in/example28",
    website: "https://www.example28.com",
    __v: 0,
  },
  {
    _id: "650ee09eaba7394f1e16ac8b",
    profileId: "8662c998-565d-406a-9fe5-9551690171b3",
    name: "Udhayakumar Ulaganathan",
    image: "",
    course: "ME / M.Tech, CSE",
    year: 2009,
    location: "Tambaram, Tamilnadu, India",
    phone: 9876543210,
    company: "ThoughtWorks Technologies Private Limited",
    designation: "Lead Consultant ",
    industry: "IT Services",
    offers: "Web Development, Software Consulting, Data Analytics",
    linkedin: "https://www.linkedin.com/in/ruudhay/",
    website: "https://www.example29.com",
    __v: 0,
  },
  {
    _id: "650ee182aba7394f1e16ac8d",
    profileId: "9e916b09-159f-4987-93cf-f9dcedc64a65",
    name: "Karthi Sekar ",
    image: "",
    course: "BE / B.Tech",
    year: 1994,
    location: "Sivakasi, Tamilnadu, India",
    phone: 9876543278,
    company: "Okulus Digital",
    designation: "Textile,Founder  ",
    industry: "Printing & Publishing",
    offers: "Printing Services, Publishing Solutions, Graphic Design",
    linkedin: "https://www.linkedin.com/in/example30",
    website: "https://www.example30.com",
    __v: 0,
  },
  {
    _id: "650ee1f2aba7394f1e16ac93",
    profileId: "d56e5522-5935-4810-a3d1-5968fec00489",
    name: "Karthi Sekar ",
    image: "",
    course: "BE / B.Tech",
    year: 1994,
    location: "Sivakasi, Tamilnadu, India",
    phone: 9876543278,
    company: "Okulus Digital",
    designation: "Textile,Founder  ",
    industry: "Printing & Publishing",
    offers: "Printing Services, Publishing Solutions, Graphic Design",
    linkedin: "https://www.linkedin.com/in/example30",
    website: "https://www.example30.com",
    __v: 0,
  },
  {
    _id: "650ee284aba7394f1e16ac95",
    profileId: "13e803c6-7371-4167-88df-7feb58268c0e",
    name: "Sandeep Balekai ",
    image: "",
    course: "BE / B.Tech",
    year: 1987,
    location: "Hosur, Tamilnadu, India",
    phone: 9898543278,
    company: "CONQUEST",
    designation: "Textile,Chief Executive ",
    industry: "Automotive",
    offers: "Car Manufacturing, Auto Parts, Electric Vehicles",
    linkedin: "https://www.linkedin.com/in/example31",
    website: "https://www.example31.com",
    __v: 0,
  },
  {
    _id: "650ee2b7aba7394f1e16ac97",
    profileId: "7feffdad-87d1-4351-a46a-fb6ee1a807fc",
    name: "SUBBAIAH S ",
    image: "",
    course: "BE / B.Tech",
    year: 1988,
    location: "Hosur, Tamilnadu, India",
    phone: 9898576278,
    company: "CONQUEST",
    designation: "Textile,Chief Executive ",
    industry: "Automotive",
    offers: "Car Manufacturing, Auto Parts, Electric Vehicles",
    linkedin: "https://www.linkedin.com/in/example32",
    website: "https://www.example32.com",
    __v: 0,
  },
  {
    _id: "650ee349aba7394f1e16ac99",
    profileId: "70618009-ca63-4cdc-bf31-d8dc259e703b",
    name: "Narayanan Alagappan",
    image: "",
    course: "BE / B.Tech Mech",
    year: 1995,
    location: "Cuddalore, Tamilnadu, India",
    phone: 9898576278,
    company: "GrandLakes",
    designation: "Director  ",
    industry: "Environmental Services",
    offers:
      "Waste Management, Environmental Consulting, Eco-friendly Solutions",
    linkedin: "https://www.linkedin.com/in/example33",
    website: "https://www.example33.com",
    __v: 0,
  },
  {
    _id: "650ee3daaba7394f1e16ac9b",
    profileId: "00dd6408-eb3b-48ba-b0e5-10cd7dff9db4",
    name: "V Ravindran",
    image: "",
    course: "BE / B.Tech Mech",
    year: 1978,
    location: "Nagercoil, Tamilnadu, India",
    phone: 6543210987,
    company: "Medicineless Theraphy for all Ailments by Terracare",
    designation: "herapist",
    industry: "Transportation",
    offers: "Logistics, Public Transit, Shipping Services",
    linkedin: "https://www.linkedin.com/in/example34",
    website: "https://www.example34.com",
    __v: 0,
  },
  {
    _id: "650ee400aba7394f1e16ac9d",
    profileId: "16f384f4-b67b-4343-ad46-04d6e94c1115",
    name: "Dhandapani Ammasai",
    image: "",
    course: "MCA",
    year: 1993,
    location: "Nagercoil, Tamilnadu, India",
    phone: 6543210987,
    company: "Medicineless Theraphy for all Ailments by Terracare",
    designation: "herapist",
    industry: "Transportation",
    offers: "Logistics, Public Transit, Shipping Services",
    linkedin: "https://www.linkedin.com/in/example35",
    website: "https://www.example35.com",
    __v: 0,
  },
  {
    _id: "650ee47eaba7394f1e16ac9f",
    profileId: "042e5674-1d05-461b-869f-e85e583d85e8",
    name: "Ravindran Durairaj",
    image: "",
    course: "BE / B.Tech ",
    year: 1979,
    location: "Nagercoil, Tamilnadu, India",
    phone: 6543210987,
    company: "BHARATH PACKAGINGS",
    designation: "CE,PARTNER ",
    industry: "Biotechnology",
    offers: "Biotech Research, Medical Devices, Genetic Engineering",
    linkedin: "https://www.linkedin.com/in/example36",
    website: "https://www.example36.com",
    __v: 0,
  },
  {
    _id: "650ee529aba7394f1e16aca1",
    profileId: "96929f04-0217-40b7-9d28-6366a7de4616",
    name: "Muthukhumaren Kpm",
    image: "",
    course: "BE / B.Tech ME (Sandwich)",
    year: 1992,
    location: "Hosur, Tamilnadu, India",
    phone: 6543298987,
    company: "KPM Plasto Rubber Co.,",
    designation: "CEO ",
    industry: "Automotive",
    offers: "Car Manufacturing, Auto Parts, Electric Vehicles",
    linkedin: "https://www.linkedin.com/in/example37",
    website: "https://www.example37.com",
    __v: 0,
  },
  {
    _id: "650ee5aaaba7394f1e16aca3",
    profileId: "81a19528-648c-494c-9746-8c70d998105c",
    name: "Arun Kumar Nair",
    image: "",
    course: "BE / B.Tech",
    year: 1984,
    location: "Ramanathapuram, Tamilnadu, India",
    phone: 9843298987,
    company: "KPM Plasto Rubber Co.,",
    designation: "Prod,Business Mentor, Process Trainer and Advisor ",
    industry: "Media",
    offers: "News Media, Advertising, Film & TV Production",
    linkedin: "https://www.linkedin.com/in/example38",
    website: "https://www.example38.com",
    __v: 0,
  },
  {
    _id: "650ee650aba7394f1e16aca5",
    profileId: "77c4eb76-d3f3-47ed-a803-a7902419a811",
    name: ".Navanithakrishnan Perumal",
    image: "",
    course: "BE / B.Tech",
    year: 1997,
    location: "Karaikudi,, Tamilnadu, India",
    phone: 9843209987,
    company: "KPM Plasto Rubber Co.,",
    designation: "CE",
    industry: "Food & Beverage",
    offers: "Food Processing, Restaurants, Beverage Production",
    linkedin: "https://www.linkedin.com/in/example39",
    website: "https://www.example39.com",
    __v: 0,
  },
  {
    _id: "650ee66faba7394f1e16aca7",
    profileId: "1e43cb96-3993-4f46-8e8d-4b06ec1d7999",
    name: "Prem Kumar Gokuladasan",
    image: "",
    course: "BE / B.Tech",
    year: 1998,
    location: "Karaikudi,, Tamilnadu, India",
    phone: 9843209987,
    company: "KPM Plasto Rubber Co.,",
    designation: "Prod",
    industry: "Food & Beverage",
    offers: "Food Processing, Restaurants, Beverage Production",
    linkedin: "https://www.linkedin.com/in/example39",
    website: "https://www.example39.com",
    __v: 0,
  },
];

export default data;
