import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ProfileCard from "@/components/Dashboard/ProfileCard";
import TopBar from "@/components/TopBar/TopBar";
import Navbar from "@/components/TopBar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>ABC Group Bio</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        {/* <Navbar /> */}
        <div className={styles.maindiv}>
          <ProfileCard />
        </div>
      </main>
    </>
  );
}
