import React, { useState, useEffect } from "react";
import { useRouter } from "next/router";
import axios from "axios";
import Image from "next/image";
import styles from "@/styles/SingleProfile.module.css";
import LinkedInIcon from "@mui/icons-material/LinkedIn";
import LinkIcon from "@mui/icons-material/Link";
import Head from "next/head";

import KeyboardBackspaceIcon from "@mui/icons-material/KeyboardBackspace";
export default function SingleProfile() {
  const router = useRouter();
  const { id } = router.query;

  const [selectedProfile, setSelectedProfile] = useState({});

  const navigateToHome = () => {
    router.push({
      pathname: "/",
    });
  };

  useEffect(() => {
    if (id) {
      axios
        .get(`${process.env.NEXT_PUBLIC_BASE_URL}/profile/${id}`)

        .then((response) => {
          setSelectedProfile(response.data);
          console.log("selectedprofile :" + JSON.stringify(response.data));
        })
        .catch((error) => {
          console.error("Error fetching data:", error);
        });
    }
  }, [id]);

  if (!selectedProfile || Object.keys(selectedProfile).length === 0) {
    return <div>Loading...</div>;
  }
  const getFirstLetterCapital = (name) => {
    return name.charAt(0).toUpperCase();
  };
  return (
    <>
      <Head>
        <title>ABC Group Bio</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        {/* <TopBar /> */}
        <div className={styles.container}>
          <KeyboardBackspaceIcon
            onClick={navigateToHome}
            style={{ marginBottom: "-2rem", cursor: "pointer" }}
          />
          <div className={styles.imageContainer}>
            <img
              src={selectedProfile.image}
              alt="image"
              style={{ width: "100%", height: "100%" }}
            />
            {/* <Image
              src={selectedProfile.photo}
              width={170}
              height={170}
              alt="image"
              className={styles.image}
            />
             */}
            {/* <div className={styles.image}>
              {selectedProfile.photo ? (
                // Display the image if it is available
                <img src={selectedProfile.photo} alt="Profile" />
              ) : (
                // Display the first letter of the name in capital if no image is available
                <div className={styles.nameInitial}>
                  <p className={styles.firstletter}>
                    {getFirstLetterCapital(selectedProfile.name)}
                  </p>
                </div>
              )}
            </div> */}
          </div>
          <div className={styles.content}>
            <div className={styles.heading}>
              <h1 className={styles.headingtext}>{selectedProfile.name}</h1>
              <div className={styles.linkicon}>
                <LinkedInIcon style={{ cursor: "pointer" }} />
                <LinkIcon style={{ cursor: "pointer" }} />
              </div>
            </div>
            <div className={styles.business}>
              <h2 className={styles.contentheading}>Business Info</h2>
              {/* <h4>{selectedProfile.name}</h4> */}
              <div className={styles.row}>
                <p className={styles.contenttext}>Role & Company </p>
                <p className={styles.span}>
                  {selectedProfile.designation}, {selectedProfile.company}
                </p>
              </div>

              <div className={styles.row}>
                <p className={styles.contenttext}>Industry </p>
                <p className={styles.span}>{selectedProfile.industry}</p>
              </div>

              <div className={styles.row}>
                <p className={styles.contenttext}>Services Offered </p>
                <p className={styles.span}>{selectedProfile.offers}</p>
              </div>
            </div>

            <div className={styles.personal}>
              <h2 className={styles.contentheading}>Personal Info</h2>
              {/* <h4>{selectedProfile.name}</h4> */}
              <div className={styles.row}>
                <p className={styles.contenttext}>Course </p>
                <p className={styles.span}>{selectedProfile.course}</p>
              </div>
              <div className={styles.row}>
                <p className={styles.contenttext}>Years</p>
                <p className={styles.span}>{selectedProfile.year}</p>
              </div>
              <div className={styles.row}>
                <p className={styles.contenttext}>Location </p>
                <p className={styles.span}>{selectedProfile.location}</p>
              </div>
              <div className={styles.row}>
                <p className={styles.contenttext}>Contact </p>
                <a className={styles.span}>{selectedProfile.phone}</a>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
